#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/logitechdaemon`
case "$1" in
  start)
    stat_busy "Starting logitech-daemon"
    [ -z "$PID" ] && /usr/bin/logitechdaemon
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/logitech-daemon.pid
      stat_done
      add_daemon logitech-daemon
    fi
    ;;
  stop)
    stat_busy "Stopping logitech-daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/logitech-daemon.pid
      stat_done
      rm_daemon logitech-daemon
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
